### ISSUE TITLE
Make /map call faster

### ISSUE THREAD

**Issue by Komzpa** [zerebubuth/openstreetmap-cgimap#122] opened 2016-12-18 00:11 UTC
Current implementation of /map call requires several database roundtrips per object.
On osm.org production, this means response is never served faster than 0.2ms * [number of database roundtrips per object] * [number of objects], effectively limiting API serving speed to 2000 objects per second.

Operations issue with more details: https://github.com/openstreetmap/operations/issues/135

I've reimplemented /map call in pure SQL, and the request in question is then served in 1.2 seconds instead of 22. Implementation is here: https://github.com/Komzpa/fastmap - feel free to grab. :)

**Comment by pnorman** [comment] 2016-12-18 09:02
I've long thought about implementing the API in pure PostgreSQL, using the Postgres XML functions and one big query. This is not because I think it's a good idea, but because I would find it interesting, in an insane query way which I like. It is in fact a horribly bad idea.

- It throws away existing work
- It makes code reuse difficult. The map call should be reusing code with other element-returning API calls
- It requires duplication for each output format
- Modifying something like this is exceptionally difficult
- Large monolithic SQL statements of this complexity are all but untestable
- Establishing correctness is very difficult

So I don't think the SQL you gave is very helpful for the task of making the map call faster.

It would be helpful to have issues about specific problems rather than a general issue.

**Comment by Komzpa** [comment] 2016-12-18 09:23
Thanks for pointing it.

Throwing away code is considered a good practice around here - it lets software redesigns happen.
I'll address the rest of issues later today.

**Comment by Komzpa** [comment] 2016-12-18 15:50
I've cleaned up functions.
 - code is now reusable, there are functions to get/serialize elements;
 - output is split from postgres tuple representation;
 - code is split into logically separate files - should be easy to find precise spot;
 - it's no longer monolithic, units are separate and testable.

Hope this helps.

**Comment by Zverik** [comment] 2016-12-19 11:35
What about a json output feature we planned for api 0.7?

**Comment by Komzpa** [comment] 2016-12-19 11:43
@Zverik is there a description of it available?

**Comment by Zverik** [comment] 2016-12-19 13:03
No there isn't, I'm talking about a possible extension that may affect this optimization. How much would need to be changed and added to support json?

**Comment by Komzpa** [comment] 2016-12-19 13:17
In current project layout it's as easy as providing a serializer for each entity, similar to this xml one, if you chose to serialize on database side: https://github.com/Komzpa/fastmap/blob/master/types/member.sql#L26

If we chose to migrate e.g. tags to a jsonb column, this part can be converted to noop for json version of API.

**Comment by gravitystorm** [comment] 2016-12-19 16:00
One of the design goals of cgimap is to work in a streaming fashion - that is, to minimise the amount of data held in the cgimap process when sending results, and therefore reduce the amount of memory being used by the cgimap processes.

I realise that asking for all the tags in one query minimises the number of queries, and also reduces the number of round trips between the servers running cgimap and the db (replica) machines. But by my understanding, this will come at the cost of increased memory consumption, especially when large map calls are slow to send to clients.

Has this been considered in the "pure sql" version?

Furthermore, there might be a balance between the two, where we could fetch tags in batches (to reduce time spent waiting on round trip times) but not hundreds of thousands at once (to reduce peak memory use). I suspect that to experiment with this, a modified version of cgimap will be required. @Komzpa what are your thoughts on this?

**Comment by Komzpa** [comment] 2016-12-19 16:13
@gravitystorm 
 * Postgres always plans a query in a way using less than `work_mem` bytes of memory;
 * Rows can be read from a connection cursor at the rate the consumer can consume them;
 * Number of concurrent fetches is limited by `max_connections`. It looks like current cgimap implementation holds a connection until the end of query, so it is wasted for longer periods of time.

**Comment by mmd-osm** [comment] 2016-12-19 21:41
Great to see some new approaches here. Any idea how response times would be for a planet db rather than a Belarus extract? I also cross checked the response times with a comparable query on the latest Overpass dev (http://overpass-turbo.eu/s/kLm), that would be around 500ms...

**Comment by Komzpa** [comment] 2016-12-19 21:54
@mmd-osm no particular reason why it should be a lot different with planet, looking at query plans. I'd be happy to check but I don't have any setup similar to main OSM database - 6TB of SSD isn't something easily found :)

A faster response time can be achieved if database structure is changed - now the tags are stored each as separate record (involving index search overhead for time and index space and tuple header overhead for disk usage), similar goes about list of way nodes (they aren't integer arrays embedded into a way but a separate table, where each node of a way has a way ID, a version of the way in historical tables, an ordering number for the node and a linked node ID, plus indexes to cope with this all) and relation members.

If that structure is simplified 500ms and faster sounds like an easily achievable thing.

**Comment by Komzpa** [comment] 2018-02-04 13:51
Per @mmd-osm and @gravitystorm in #140, this issue was addressed by PRs #130 and #136.

On main osm.org, time for my reference query is now not 22s but 9s. Good work!

```
kom@routecat:~$ time curl -H "Accept-Encoding: gzip" "http://www.openstreetmap.org/api/0.6/map?bbox=27.61649608612061,53.85379229563698,27.671985626220707,53.886459293813054" > /dev/null
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 1239k    0 1239k    0     0   137k      0 --:--:--  0:00:09 --:--:--  259k

real    0m9.038s
user    0m0.017s
sys     0m0.020s
```

Still, a local test with https://github.com/Komzpa/fastmap shows 2s, so there is still room for optimization.

**Comment by zerebubuth** [comment] 2018-02-04 13:57
> Still, a local test with https://github.com/Komzpa/fastmap shows 2s, so there is still room for optimization.

Out of interest, what does a local test with cgimap show?

**Comment by Komzpa** [comment] 2018-02-04 14:23
@zerebubuth for exact digits:
```
kom@junocat fastmap % time cat fastmap.sql | sed s/--explain/explain/g | sed 's/: xml/: text/g' | psql -q > explain_analyze_buffers.txt

cat fastmap.sql  0,00s user 0,00s system 76% cpu 0,001 total
sed s/--explain/explain/g  0,00s user 0,00s system 89% cpu 0,001 total
sed 's/: xml/: text/g'  0,00s user 0,00s system 89% cpu 0,001 total
psql -q > explain_analyze_buffers.txt  0,04s user 0,02s system 4% cpu 1,371 total

kom@junocat ~ % time curl -H "Accept-Encoding: gzip" "http://localhost:31337/api/0.6/map?bbox=27.61649608612061,53.85379229563698,27.671985626220707,53.886459293813054" > /dev/null      

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 1716k  100 1716k    0     0   429k      0  0:00:04  0:00:04 --:--:--  402k
curl -H "Accept-Encoding: gzip"  > /dev/null  0,00s user 0,01s system 0% cpu 4,270 total

```

**Comment by Komzpa** [comment] 2018-02-04 14:26
according to postgres log is issues screens and screens of similar queries:

```
2018-02-04 14:24:50 GMT [28621-2096] gis@gis LOG:  statement: select u.data_public, u.display_name, u.id from users u join changesets c on u.id=c.user_id where c.id=15593467
2018-02-04 14:24:50 GMT [28621-2097] gis@gis LOG:  statement: select u.data_public, u.display_name, u.id from users u join changesets c on u.id=c.user_id where c.id=36288651
2018-02-04 14:24:50 GMT [28621-2098] gis@gis LOG:  statement: select u.data_public, u.display_name, u.id from users u join changesets c on u.id=c.user_id where c.id=19033981
2018-02-04 14:24:50 GMT [28621-2099] gis@gis LOG:  statement: select u.data_public, u.display_name, u.id from users u join changesets c on u.id=c.user_id where c.id=19033338
2018-02-04 14:24:50 GMT [28621-2100] gis@gis LOG:  statement: select u.data_public, u.display_name, u.id from users u join changesets c on u.id=c.user_id where c.id=19663836
2018-02-04 14:24:50 GMT [28621-2101] gis@gis LOG:  statement: select u.data_public, u.display_name, u.id from users u join changesets c on u.id=c.user_id where c.id=21313429
2018-02-04 14:24:50 GMT [28621-2102] gis@gis LOG:  statement: select u.data_public, u.display_name, u.id from users u join changesets c on u.id=c.user_id where c.id=3006120
2018-02-04 14:24:50 GMT [28621-2103] gis@gis LOG:  statement: select u.data_public, u.display_name, u.id from users u join changesets c on u.id=c.user_id where c.id=15079404
2018-02-04 14:24:50 GMT [28621-2104] gis@gis LOG:  statement: select u.data_public, u.display_name, u.id from users u join changesets c on u.id=c.user_id where c.id=14770838
2018-02-04 14:24:50 GMT [28621-2105] gis@gis LOG:  statement: select u.data_public, u.display_name, u.id from users u join changesets c on u.id=c.user_id where c.id=40297820
2018-02-04 14:24:50 GMT [28621-2106] gis@gis LOG:  statement: select u.data_public, u.display_name, u.id from users u join changesets c on u.id=c.user_id where c.id=16627182
2018-02-04 14:24:50 GMT [28621-2107] gis@gis LOG:  statement: select u.data_public, u.display_name, u.id from users u join changesets c on u.id=c.user_id where c.id=19614747
2018-02-04 14:24:50 GMT [28621-2108] gis@gis LOG:  statement: select u.data_public, u.display_name, u.id from users u join changesets c on u.id=c.user_id where c.id=21607160
2018-02-04 14:24:50 GMT [28621-2109] gis@gis LOG:  statement: select u.data_public, u.display_name, u.id from users u join changesets c on u.id=c.user_id where c.id=9063603
2018-02-04 14:24:50 GMT [28621-2110] gis@gis LOG:  statement: select u.data_public, u.display_name, u.id from users u join changesets c on u.id=c.user_id where c.id=28008682
2018-02-04 14:24:50 GMT [28621-2111] gis@gis LOG:  statement: select u.data_public, u.display_name, u.id from users u join changesets c on u.id=c.user_id where c.id=27570704
2018-02-04 14:24:50 GMT [28621-2112] gis@gis LOG:  statement: select u.data_public, u.display_name, u.id from users u join changesets c on u.id=c.user_id where c.id=32260897
2018-02-04 14:24:50 GMT [28621-2113] gis@gis LOG:  statement: select u.data_public, u.display_name, u.id from users u join changesets c on u.id=c.user_id where c.id=1844643
2018-02-04 14:24:50 GMT [28621-2114] gis@gis LOG:  statement: select u.data_public, u.display_name, u.id from users u join changesets c on u.id=c.user_id where c.id=473491
2018-02-04 14:24:50 GMT [28621-2115] gis@gis LOG:  statement: select u.data_public, u.display_name, u.id from users u join changesets c on u.id=c.user_id where c.id=6608756
2018-02-04 14:24:50 GMT [28621-2116] gis@gis LOG:  statement: select u.data_public, u.display_name, u.id from users u join changesets c on u.id=c.user_id where c.id=19784126
2018-02-04 14:24:50 GMT [28621-2117] gis@gis LOG:  statement: select u.data_public, u.display_name, u.id from users u join changesets c on u.id=c.user_id where c.id=31722028
2018-02-04 14:24:50 GMT [28621-2118] gis@gis LOG:  statement: select u.data_public, u.display_name, u.id from users u join changesets c on u.id=c.user_id where c.id=6758699
2018-02-04 14:24:50 GMT [28621-2119] gis@gis LOG:  statement: select u.data_public, u.display_name, u.id from users u join changesets c on u.id=c.user_id where c.id=17238366
2018-02-04 14:24:50 GMT [28621-2120] gis@gis LOG:  statement: select u.data_public, u.display_name, u.id from users u join changesets c on u.id=c.user_id where c.id=27774903
2018-02-04 14:24:50 GMT [28621-2121] gis@gis LOG:  statement: select u.data_public, u.display_name, u.id from users u join changesets c on u.id=c.user_id where c.id=5776453
2018-02-04 14:24:50 GMT [28621-2122] gis@gis LOG:  statement: select u.data_public, u.display_name, u.id from users u join changesets c on u.id=c.user_id where c.id=28014638
2018-02-04 14:24:50 GMT [28621-2123] gis@gis LOG:  statement: select u.data_public, u.display_name, u.id from users u join changesets c on u.id=c.user_id where c.id=29854573
```

**Comment by Komzpa** [comment] 2018-02-04 14:32
To see such thing locally:

```
alter system set log_statement to 'all';
select pg_reload_conf();
```

and have a look at the postgres log. 

If you like to have it on console (or god forbid gdb), stop it systemwide and do this as `postgres` user:

```
/usr/lib/postgresql/10/bin/postgres -D /etc/postgresql/10/main/
```

**Comment by zerebubuth** [comment] 2018-02-04 15:27
Ah, yes, that's a good point. On a cold-start the changeset/user cache will be empty, and it'll do a lot of small queries. I would hope that subsequent requests are faster, although the [default cache size of 1,000 items](https://github.com/zerebubuth/openstreetmap-cgimap/blob/e78578817f4b8f66dfc4e0b91ca1bcfe82cd047c/src/backend/apidb/apidb.cpp#L14) seems too small. That request alone references 2,282 changesets. Perhaps we should bump the default up to 10,000? Or query them explicitly ahead of extracting the elements which depend on them?

**Comment by Komzpa** [comment] 2018-02-04 15:40
A proper way would be just a plain `join` on them. Let the database system decide on when (and what) to cache, whether to perform merge or hash join, depending on the data histogram stats. I expect cache of 1k or 10k (and maybe even 100k) elements to be unnoticeable on osm.org load spread.

**Comment by mmd-osm** [comment] 2018-02-04 16:40
No doubt we also have some buffering & caching effects here. Running this map call a number of times on osm.org eventually gets response times around 5s, with the very first call around 9s here.

**Comment by Komzpa** [comment] 2018-02-04 17:19
@mmd-osm I don't have any production osm data.

If you were asking about theoretical performance in fasmap, here's its explain: https://github.com/Komzpa/fastmap/blob/master/explain_analyze_buffers.txt

**Comment by mmd-osm** [comment] 2018-02-04 17:21
Ah, forgot to mention, aggregated stats for your local cgimap test.

**Comment by Komzpa** [comment] 2018-02-04 17:36
sorry, no aggregations, just a piece of log that scrollback saved:
https://gist.github.com/Komzpa/52c6574a9b1c48a9177d9a4520c492e2

**Comment by mmd-osm** [comment] 2018-02-04 18:25
So, the issue is most obvious here: https://github.com/zerebubuth/openstreetmap-cgimap/blob/master/src/backend/apidb/common_pgsql_selection.cpp#L194-L209 and https://github.com/zerebubuth/openstreetmap-cgimap/blob/master/src/backend/apidb/common_pgsql_selection.cpp#L16

Although we have the full list of rows from a previous selection available, db lookup for changeset is done one by one. Could be fixed by doing a bulk cache prefetch for missing changeset details. It's a bit tricky, as the cache only support single value lookups at this time (https://github.com/zerebubuth/openstreetmap-cgimap/blob/master/include/cgimap/backend/apidb/cache.hpp#L111)

Do you see some other cpu consumption in cgimap itself, or it the other time all spent somewhere with db selects?

**Comment by Komzpa** [comment] 2018-02-04 18:48
I have not performed testing to this level of granularity, just `time curl`. I expect these roundtrips to be the biggest time consumer, after getting which fixed we'll start seeing CPU load on both postgres and cgimap :)

You also need to make sure your cache is big enough to fit all the values you are going to prefetch. We're now limiting to 50k nodes plus their ways plus their nodes plus relations, so 100k looks good enough for a big request not to was every bit away, but just most of them.

**Comment by mmd-osm** [comment] 2018-04-23 20:00
A few pointers to mass read changeset details and prefetch cache contents:

apidb.cpp:
----------

```
#define CACHE_SIZE 1000   
```

Increase to 10000?


common_pgsql_selection.cpp:
---------------------------

```
template <typename T>
void extract(
  const pqxx::result &rows, output_formatter &formatter,
  cache<osm_changeset_id_t, changeset> &cc) {

  element_info elem;
  typename T::extra_info extra;
  tags_t tags;
```

<<< Add for (const auto & row : rows) and collect all elem.changeset in vector

<<< cc.prefetch( ... vector with changesets ... );

```
  for (const auto &row : rows) {
    extract_elem(row, elem, cc);
    extra.extract(row);
```

changeset.cpp:
--------------

```
 *fetch_changeset(pqxx::transaction_base &w, osm_changeset_id_t id)
```

-> change osm_changeset_id_t to std::vector< osm_changeset_id_t >

-> mass enable method:
   - mass DB selection with list of changeset ids
   - return vector of all changesets


cache.hpp:
----------

Add new method "prefetch", input: vector of Key
Check which parts in method get can be reused for mass processing

:get method: result(fetch(k));   -> change to single element vector with one entry "k".

**Comment by mmd-osm** [comment] 2018-04-28 09:27
Hey @Komzpa : do you still have your test set up around? Could you run another test on https://github.com/mmd-osm/openstreetmap-cgimap/tree/patch/cache_prefetch? It should remove all those single selects by a mass fetch.

**Closed** 2018-07-20 19:45 UTC

**Comment by mmd-osm** [comment] 2020-08-02 07:47
As @Zverik started in http://shtosm.ru/all/gonka-za-json/ that the API still does one query per object: that’s not the case, all performance issues mentioned in this issue have been addressed in the meantime.
